spring:
  jpa:
    hibernate:
      ddl-auto: create # each time program is ran, start with fresh tables and data
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/carservice"
    username: carservice
    password: root # local file for dev work, won't be checked in